name: Build and Push
on:
  push:
    branches: [gitops]
    paths: ['index.js', 'Dockerfile', 'package*.json']

permissions:
  contents: write

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::318630425437:role/devops-challenge-2-github-actions
      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        env:
          ECR_REPO: ${{ steps.ecr-login.outputs.registry }}/devops-challenge-2-app
          TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REPO:$TAG .
          docker push $ECR_REPO:$TAG

      - name: Update Helm values with new tag
        env:
          TAG: ${{ github.sha }}
        run: |
          sed -i "s/tag: .*/tag: \"$TAG\"/" helm/hello-world/values.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Deploy $TAG"
          git push
